- name: Install SSM on Amazon Linux 1
  yum:
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    state: present

- name: Enable and Start SSM on Amazon Linux 1
  systemd:
    name: amazon-ssm-agent
    state: started
    enabled: yes

- name: Restart SSM on Amazon Linux 1
  systemd:
    name: amazon-ssm-agent
    state: restarted
