- name: Install SSM
  include: AMZL2_RHEL7_COS7.yml
  when: > 
   ( ansible_distribution == "CentOS" and
     ansible_distribution_major_version == "7" )
   or
   ( ansible_distribution == "RedHat" and
     ansible_distribution_major_version == "7" )
   or
   ( ansible_distribution == "Amazon" and
     ansible_distribution_major_version == "2" )

- include: AMZL1.yml
  when:
   - ansible_distribution == "Amazon" and ansible_distribution_major_version == "1"

- include: COS6.yml
  when:
   - ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- include: RHEL8_COS8.yml
  when: >
   ( ansible_distribution == "CentOS" and
     ansible_distribution_major_version == "8" )
   or
   ( ansible_distribution == "RedHat" and
     ansible_distribution_major_version == "8" )

- include: D8_D9.yml
  when: >
   ( ansible_distribution == "Debian" and
     ansible_distribution_major_version == "8" )
   or
   ( ansible_distribution == "Debian" and
     ansible_distribution_major_version == "9" )

- include: U16_18_20.yml
  when:
   - ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

- include: U14.yml
  when:
   - ansible_distribution == "Ubuntu"
   - ansible_distribution_major_version == "14"

- include: U16_18_20.yml
  when:
   - ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"

- include: U16_18_20.yml
  when:
   - ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20"
