- name: install the ssm deb on Ubuntu 14
  apt:
    deb: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
    state: present

- name: enable and start ssm service
  service:
    name: amazon-ssm-agent
    state: started
    enabled: yes

- name: Restart ssm service
  service:
    name: amazon-ssm-agent
    state: restarted
